wandb_version: 1

dataset:
  desc: null
  value:
    download_first: false
    urls:
    - jsb_chorales.pickle: https://d2hg8soec8ck9v.cloudfront.net/datasets/polyphonic/jsb_chorales.pickle
    - piano_midi.pickle: https://d2hg8soec8ck9v.cloudfront.net/datasets/polyphonic/piano_midi.pickle
    - muse_data.pickle: https://d2hg8soec8ck9v.cloudfront.net/datasets/polyphonic/muse_data.pickle
    - nottingham.pickle: https://d2hg8soec8ck9v.cloudfront.net/datasets/polyphonic/nottingham.pickle
    path: data/jsb_chorales.pickle
    split: train
model:
  desc: null
  value:
    input_dim: 88
    hidden_dim: 400
    hidden_dim_em: 100
    hidden_dim_tr: 200
    latent_dim: 100
train:
  desc: null
  value:
    epochs: 100
    batch_size: 64
    num_workers: 4
    lr: 0.001
    save_model: true
    save_dir: saved_models
    save_every: 10
    proj_name: train_dvae
    wandb_user_name: farrinfedra
_wandb:
  desc: null
  value:
    python_version: 3.9.6
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1701805744.936682
    t:
      1:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.9.6
      5: 0.16.0
      8:
      - 5
      13: darwin-arm64
